name = "dmzj-zerg"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-05-30"

# 打包器
[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

# 调度器
[triggers]
crons = ["* * * * 3"]